import StyleDictionary from 'style-dictionary';
import { registerCustomTransforms } from './transforms/custom-transforms.js';

// Register custom transforms
registerCustomTransforms(StyleDictionary);

// Register a shared file header
StyleDictionary.registerFileHeader({
  name: 'cycleAlarmHeader',
  fileHeader: () => ['Auto-generated by Style Dictionary — DO NOT EDIT'],
});

// Register custom transform groups that treat dimension values as raw pt/dp
// instead of applying the built-in rem-to-pt/dp conversions.
StyleDictionary.registerTransformGroup({
  name: 'ios-swift/pt',
  transforms: [
    'attribute/cti',
    'name/camel',
    'color/UIColorSwift',
    'content/swift/literal',
    'asset/swift/literal',
    'size/cgfloat',
    'time/seconds',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'compose/dp',
  transforms: [
    'attribute/cti',
    'name/camel',
    'color/composeColor',
    'size/compose/dp',
    'time/compose/ms',
  ],
});

// Token category definitions used to generate per-file filters
const tokenGroups = [
  { category: 'color', iosFile: 'CycleColors.swift', androidFile: 'CycleColors.kt', className: 'CycleColors' },
  { category: 'spacing', iosFile: 'CycleSpacing.swift', androidFile: 'CycleSpacing.kt', className: 'CycleSpacing' },
  { category: 'radius', iosFile: 'CycleRadius.swift', androidFile: 'CycleRadius.kt', className: 'CycleRadius' },
  { category: 'typography', iosFile: 'CycleTypography.swift', androidFile: 'CycleTypography.kt', className: 'CycleTypography' },
  { category: 'animation', iosFile: 'CycleAnimation.swift', androidFile: 'CycleAnimation.kt', className: 'CycleAnimation' },
];

function makeFilter(category) {
  return (token) => token.path[0] === category;
}

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    ios: {
      transformGroup: 'ios-swift/pt',
      buildPath: 'build/ios/',
      options: {
        fileHeader: 'cycleAlarmHeader',
      },
      files: tokenGroups.map(({ category, iosFile, className }) => ({
        destination: iosFile,
        format: 'ios-swift/enum.swift',
        filter: makeFilter(category),
        options: {
          className,
        },
      })),
    },
    android: {
      transformGroup: 'compose/dp',
      buildPath: 'build/android/',
      options: {
        fileHeader: 'cycleAlarmHeader',
      },
      files: tokenGroups.map(({ category, androidFile, className }) => ({
        destination: androidFile,
        format: 'compose/object',
        filter: makeFilter(category),
        options: {
          className,
          packageName: 'com.cyclealarm.tokens',
        },
      })),
    },
  },
};
