import StyleDictionary from 'style-dictionary';
import { registerCustomTransforms } from './transforms/custom-transforms.js';

// Register custom transforms
registerCustomTransforms(StyleDictionary);

// Register a shared file header
StyleDictionary.registerFileHeader({
  name: 'chronirHeader',
  fileHeader: () => ['Auto-generated by Style Dictionary — DO NOT EDIT'],
});

// Register custom transform groups that treat dimension values as raw pt/dp
// instead of applying the built-in rem-to-pt/dp conversions.
StyleDictionary.registerTransformGroup({
  name: 'ios-swift/pt',
  transforms: [
    'attribute/cti',
    'name/camel',
    'color/UIColorSwift',
    'content/swift/literal',
    'asset/swift/literal',
    'size/cgfloat',
    'time/seconds',
  ],
});

StyleDictionary.registerTransformGroup({
  name: 'compose/dp',
  transforms: [
    'attribute/cti',
    'name/camel',
    'color/composeColor',
    'size/compose/dp',
    'time/compose/ms',
  ],
});

// Token category definitions used to generate per-file filters
const tokenGroups = [
  { category: 'color', iosFile: 'ChronirColors.swift', androidFile: 'ChronirColors.kt', className: 'ChronirColors' },
  { category: 'spacing', iosFile: 'ChronirSpacing.swift', androidFile: 'ChronirSpacing.kt', className: 'ChronirSpacing' },
  { category: 'radius', iosFile: 'ChronirRadius.swift', androidFile: 'ChronirRadius.kt', className: 'ChronirRadius' },
  { category: 'typography', iosFile: 'ChronirTypography.swift', androidFile: 'ChronirTypography.kt', className: 'ChronirTypography' },
  { category: 'animation', iosFile: 'ChronirAnimation.swift', androidFile: 'ChronirAnimation.kt', className: 'ChronirAnimation' },
];

function makeFilter(category) {
  return (token) => token.path[0] === category;
}

export default {
  source: ['tokens/**/*.json'],
  platforms: {
    ios: {
      transformGroup: 'ios-swift/pt',
      buildPath: 'build/ios/',
      options: {
        fileHeader: 'chronirHeader',
      },
      files: tokenGroups.map(({ category, iosFile, className }) => ({
        destination: iosFile,
        format: 'ios-swift/enum.swift',
        filter: makeFilter(category),
        options: {
          className,
        },
      })),
    },
    android: {
      transformGroup: 'compose/dp',
      buildPath: 'build/android/',
      options: {
        fileHeader: 'chronirHeader',
      },
      files: tokenGroups.map(({ category, androidFile, className }) => ({
        destination: androidFile,
        format: 'compose/object',
        filter: makeFilter(category),
        options: {
          className,
          packageName: 'com.chronir.tokens',
        },
      })),
    },
  },
};
